# Generated by Django 5.2.4 on 2025-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('fecha', models.CharField(max_length=150)),
                ('entrada', models.CharField(max_length=150)),
                ('salida', models.CharField(max_length=150)),
            ],
        ),
    ]
