# Generated by Django 5.2.4 on 2025-07-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_perfil_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('guardia', 'Guardia'), ('especialista', 'Especialista')], default='guardia', max_length=22),
        ),
    ]
