# Generated by Django 5.2.4 on 2025-07-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('guardia', 'Guardia'), ('especialista', 'Especialista'), ('especialista_principal', 'Especialista Principal')], default='guardia', max_length=22),
        ),
    ]
